version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: wedding-gallery:latest
    container_name: wedding-gallery-api
    volumes:
      - .:/home/django/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: wedding-gallery-db
    tty: true
    environment:
      - POSTGRES_DB=wedding-gallery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.docker/.pgdata:/var/lib/postgresql/data