version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: wedding-gallery:dev
    container_name: wedding-gallery-api
    command: sleep infinity
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: wedding-gallery-db
    tty: true
    environment:
      - POSTGRES_DB=wedding-gallery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.devcontainer/.pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_FORWARD_PORT:-5432}:5432